Add annotation reader cache and fix doctrine typeGuesser
overblog/GraphQLBundle pull request #867
Opened 2021-06-22 15:43 UTC by Damienbelingheri

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | yes
| Tests pass?   | yes
| Documented?   | no
| Fixed tickets | #818 & #856
| License       | MIT

Add an cache for annotations reader to improve performances.
And fix doctrine typeGuesser with doctrine 2.9

2021-06-23 07:26 UTC, Vincz submitted a review, later dismissed

2021-06-23 09:48 UTC, mcg-web commented on docs/annotations/index.md
> +To use annoation, you must instal   '  '' ' and use the annatotton mapping type
remove this please

2021-06-23 09:48 UTC, mcg-web commented on composer.json
> +    "keywords": [
revert all changes on this file please.

2021-06-23 09:48 UTC, mcg-web commented on src/Config/Parser/AnnotationParser.php
> +                // @codeCoverageIgnoreStart
we ignore a lot of code here can we add tests to cover these intead ?

2021-07-28 16:00 UTC, Vincz approved these changes

2021-09-22 14:26 UTC, mcg-web requested changes
Look good to me, can you just revert master changes from 0.14 branch please, before merging this ?

2021-09-22 14:26 UTC, mcg-web commented on README.md
> +![CI](https://github.com/overblog/GraphQLBundle/workflows/CI/badge.svg?branch=master)
Revert please

2021-09-22 14:26 UTC, mcg-web commented on composer.json
> +            "dev-master": "1.0-dev"
Revert please

2021-09-24 14:02 UTC, mcg-web approved these changes

2021-11-26 07:39 UTC, merged